name: Build

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    name: Build ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            runner: windows-latest
            target: x86_64-pc-windows-msvc
            archive: zmk-battery-center-trafficmonitor-plugin-windows-x86_64.zip
    steps:
      - name: Check out source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Rust
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # v1
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Build plugin
        run: cargo build --locked --release --target "${{ matrix.target }}"

      - name: Package plugin
        shell: pwsh
        run: |
          Compress-Archive `
            -Path "target/${{ matrix.target }}/release/zmk_battery_center_trafficmonitor_plugin.dll" `
            -DestinationPath "${{ matrix.archive }}" `
            -CompressionLevel Optimal

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ matrix.archive }}
          path: ${{ matrix.archive }}
          if-no-files-found: error
